--- #YAML:1.0
name:                     Labyrinth-Plugin-CPAN
version:                  3.50
abstract:                 CPAN Testers plugin for the Labyrinth framework
author:
  - Barbie <barbie@cpan.org>

license:                  artistic_2
distribution_type:        module
installdirs:              site

requires:
  perl:                     5.006
  Class::Accessor::Fast:    0
  Email::Address:           0
  Labyrinth:                5.20
  Labyrinth::Plugin::Core:  5.15
  Sort::Versions:           0
recommends:
  Test::CPAN::Meta:         0
  Test::CPAN::Meta::JSON:   0
  Test::Pod:                1.00
  Test::Pod::Coverage:      0.08
build_requires:
  IO::File:                 0
  Test::More:               0.70

provides:
  Labyrinth::Plugin::CPAN:
    file:     lib/Labyrinth/Plugin/CPAN.pm
    version:  3.50

no_index:
  directory:
    - examples
    - t
    - vhost

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Labyrinth-Plugin-CPAN
  repository: http://github.com/barbie/labyrinth-plugin-cpan

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0
